### ISSUE TITLE
applying diffs that move files

### ISSUE THREAD

**Issue by lcoote** [vmware/jenkins-reviewbot#13]
review builds for diffs that move existing files to new locations consistently fail. on closer inspection of the workspace, I notice that when the diff was applied these files were not moved and were kept in their old locations, leading o predictable compile errors.

I suspect this is an issue with the diff tool (https://github.com/cloudbees/diff4j) and I will try to repro with the patch parameter plugin but I am curious - this happens so consistently for me that I am surprised that no one else has mentioned it, leading me to suspect i might be doing something wrong.

has anyone else seen this behavior?

**Comment by moorecm** [comment]
I've been seeing this a lot lately too.  Adding new files and changing files seems to work fine.  Commits with "hg mv" in them seem to be problematic.

**Comment by moorecm** [comment]
One more note:  I'm also seeing the message "Jenkins could not test these changes [...]" which does not include any indication of which build it relates to.  It would be nice to get a hyperlink in this case, too.

**Comment by yardena** [comment]
@moorecm adding build url to the message should be fairly easy, please file a separate issue. 
As for the problem with applying certain patches - by default the plugin uses diff4j, so I have no control over bugs there, but some time ago I did add a mechanism to bypass diff4j and to provide your own patch applying command, I believe in case of Mercurial it's "hg import patch.diff", so you could probably try https://wiki.jenkins-ci.org/display/JENKINS/Jenkins-Reviewbot#Jenkins-Reviewbot-Custompatchapplicationcommand.

**Comment by moorecm** [comment]
Will do.  I haven't upgraded to that version yet but I will give it a try.  I seem to recall an issue where someone asked for that too.

**Comment by yardena** [comment]
https://github.com/vmware/jenkins-reviewbot/issues/16
