### ISSUE TITLE
Make link clickable

### ISSUE THREAD

**Issue by misery** [vmware/jenkins-reviewbot#14]
Hi there!

I like to request that the posted link to the jenkins instance should be clickable in the review comment. It is really annoying to copy+paste that link. :-)

Maybe this could help:
https://www.reviewboard.org/docs/manual/2.0/webapi/2.0/rich-text-fields/#webapi2-0-text-fields

**Comment by yardena** [comment]
Our Reviewboard instance makes links clickable automatically, so I won't be able to test. Can you tell me what exactly needs to be done in the POST request for the comment to display a clickable link in your review?

**Comment by misery** [comment]
I tested that patch on reviewboard 2.0.12. This fixed my unclickable link here.
Maybe the link text could be better instead of the link itself. ;-)

https://www.reviewboard.org/docs/manual/2.0/users/markdown/#links


```
diff --git a/src/main/java/org/jenkinsci/plugins/jenkinsreviewbot/ReviewboardConnection.java b/src/main/java/org/jenkinsci/plugins/jenkinsreviewbot/ReviewboardConnection.java
index 012ccaf..e231e33 100644
--- a/src/main/java/org/jenkinsci/plugins/jenkinsreviewbot/ReviewboardConnection.java
+++ b/src/main/java/org/jenkinsci/plugins/jenkinsreviewbot/ReviewboardConnection.java
@@ -177,6 +177,7 @@ public class ReviewboardConnection {
     post.setDoAuthentication(true);
     NameValuePair[] data = {
         new NameValuePair("body_top", msg),
+        new NameValuePair("body_top_text_type", "markdown"),
         new NameValuePair("public", "true"),
         new NameValuePair("ship_it", String.valueOf(shipIt))
     };
diff --git a/src/main/java/org/jenkinsci/plugins/jenkinsreviewbot/ReviewboardNotifier.java b/src/main/java/org/jenkinsci/plugins/jenkinsreviewbot/ReviewboardNotifier.java
index 8c5c177..aa4657a 100644
--- a/src/main/java/org/jenkinsci/plugins/jenkinsreviewbot/ReviewboardNotifier.java
+++ b/src/main/java/org/jenkinsci/plugins/jenkinsreviewbot/ReviewboardNotifier.java
@@ -78,6 +78,7 @@ public class ReviewboardNotifier extends Notifier implements MatrixAggregatable
     Result result = build.getResult();
     try {
       String link = build.getEnvironment(listener).get("BUILD_URL");
+      link = "[" + link + "](" + link + ")";
       boolean patchFailed = rbParam.isPatchFailed();
       boolean success = result.equals(Result.SUCCESS);
       boolean unstable = result.equals(Result.UNSTABLE);

```

**Comment by yardena** [comment]
Thanks, will add this option in "post comment" notifier.

**Comment by misery** [comment]
Thanks! But I still have now clickable link here after an reviewbot update... do I need to set another option in reviewboard itself?

**Comment by yardena** [comment]
Yea, please tick a checkbox in the notifier section.

**Comment by misery** [comment]
I enabled "Use markdown when posting the comment" in jenkins notifier. But still no link here.

**Comment by yardena** [comment]
Sorry for the obvious question - did you pick latest plugin (2.2)? Because I just verified and NameValuePair("body_top_text_type", "markdown") is sent to Reviewboard...

**Comment by misery** [comment]
Yes, I'm using 2.2 and I can see that "markdown" is sent to Reviewboard. But it won't be unclickable until I add something like this:

```
--- a/src/main/java/org/jenkinsci/plugins/jenkinsreviewbot/ReviewboardNotifier.java
+++ b/src/main/java/org/jenkinsci/plugins/jenkinsreviewbot/ReviewboardNotifier.java
@@ -84,6 +84,10 @@ public class ReviewboardNotifier extends Notifier implements MatrixAggregatable
     Result result = build.getResult();
     try {
       String link = build.getEnvironment(listener).get("BUILD_URL");
+      if (useMarkdown) {
+        String name = link.substring(link.indexOf("/job/") + 4);
+        link = "[" + name + "](" + link + ")";
+      }
       boolean patchFailed = rbParam.isPatchFailed();
       boolean success = result.equals(Result.SUCCESS);
       boolean unstable = result.equals(Result.UNSTABLE);
```

**Comment by yardena** [comment]
Ok, will try to fix that too

**Comment by yardena** [comment]
BTW according to https://www.reviewboard.org/docs/manual/2.0/users/markdown/ "In most cases, you won’t need to build your links yourself. Any URLs that are included in your text will automatically be turned into links. In addition, certain special strings like “bug 234” or “/r/583” will be automatically linked to the relevant bug or review request." That's indeed how it works in our instance, do you know why this is different for you?

**Comment by misery** [comment]
I saw that, too. But I don't know why our reviewboard don't show it. I'm using it in a docker image that is linked from reviewboard.org itself. So there is no special configuration.

**Comment by misery** [comment]
Looks like a regression.
https://code.google.com/p/reviewboard/issues/detail?id=3754

Anyway, it would be nice if the shown url could be sliced like in my example. I don't think that the whole hostname and path is interesting every time.

**Comment by misery** [comment]
Thank you very much! I don't want to get on your nerves ... but... ;-)
"[build result]" will be print for EVERY comment. But we have different jobs that would post a comment. If everyone would use [build result] we cannot se which job added the comment. So it would be better to know at least the job name. :-)

**Comment by yardena** [comment]
Should be Ok now :-)
