### ISSUE TITLE
Support "hg patches" directly

### ISSUE THREAD

**Issue by misery** [vmware/jenkins-reviewbot#16]
Hi there!

We are using mercurial to upload patches to reviewboard and some patches cannot be applied with patch plugin but they are correct.
Since patch plugin implements their own algorithm to apply diffs it would be helpful if an "hg patch" could be import by hg instead.

As I don't know jenkins API much I added a little placeholder for it. The idea is to check the first line if it is an exported patch of mercurial (hg export). If it is an hg patch it can be added with "hg import" and let mercurial do the work. HG should know how to do it right. ;-)

It should be enough to just call hg and check the return code. Maybe it needs to check if the current directory contains a ".hg" directory before checking the first line.

```
--- a/src/main/java/org/jenkinsci/plugins/jenkinsreviewbot/ReviewboardParameterValue.java
+++ b/src/main/java/org/jenkinsci/plugins/jenkinsreviewbot/ReviewboardParameterValue.java
@@ -241,16 +241,24 @@ public class ReviewboardParameterValue extends ParameterValue {
     private static final long serialVersionUID = 1L;
 
     public Void invoke(File diff, VirtualChannel channel) throws IOException, InterruptedException {
-      ContextualPatch patch = ContextualPatch.create(diff,diff.getParentFile());
-      try {
-        List<ContextualPatch.PatchReport> reports = patch.patch(false);
-        for (ContextualPatch.PatchReport r : reports) {
-          Throwable failure = r.getFailure();
-          if (failure != null)
-            throw new IOException("Failed to patch " + r.getFile(), failure);
+      String firstLine = (new BufferedReader(new FileReader(diff))).readLine();
+      if ("# HG changeset patch".equals(firstLine))
+      {
+        // call "hg import diff.getAbsolutePath()" and check return code
+      }
+      else
+      {
+        ContextualPatch patch = ContextualPatch.create(diff,diff.getParentFile());
+        try {
+          List<ContextualPatch.PatchReport> reports = patch.patch(false);
+          for (ContextualPatch.PatchReport r : reports) {
+            Throwable failure = r.getFailure();
+            if (failure != null)
+              throw new IOException("Failed to patch " + r.getFile(), failure);
+          }
+        } catch (PatchException e) {
+          throw new IOException2("Failed to apply the patch: "+diff,e);
         }
-      } catch (PatchException e) {
-        throw new IOException2("Failed to apply the patch: "+diff,e);
       }
       return null;
     }

```

**Comment by misery** [comment]
Maybe an option for every build job to disable patch applying could be enough. So everyone could try hg import with downloaded diff in a shell command just before build command.

**Comment by moorecm** [comment]
I may have just opened an issue for the same thing.  I'm not seeing any obvious errors in the console output, though.  Is there a better place to see the patching going on?

**Comment by yardena** [comment]
Working on it...

**Comment by misery** [comment]
Thanks! Works without problems here! :-)
