### ISSUE TITLE
Repository dropdown doesn't refresh

### ISSUE THREAD

**Issue by moorecm** [vmware/jenkins-reviewbot#17]
In ReviewboardPollingBuilder.java, if 'repositories' has already been populated via loadRepositories(), it doesn't try again.

    public ListBoxModel doFillReviewbotRepoIdItems() {
      // populate list of repositories with (name, id)
      ListBoxModel items = new ListBoxModel();
      // select option to allow polling requests for all repositories
      items.add("-- any --", "-1");
      //if no repositories - try to load them again
      if (repositories.isEmpty()) loadRepositories();
      // select options to filter by repository id.
      for (Map.Entry<String, Integer> e: repositories.entrySet()) {
        items.add(e.getKey(), e.getValue().toString());
      }
      return items;
    }

It spent a couple hours this morning chasing down why my repository is not showing up in the dropdown and it seems to be because it was configured in ReviewBoard after my Jenkins job was configured for another repo..  Restarting Jenkins fixed the dropdown contents but it would be nice if it would fetch new content each time you go in to Configure in the job.

**Comment by yardena** [comment]
Originally repositories were fetched on the fly, then I added caching because we have insanely large list of Reviewboard repositories and a lousy connection between Jenkins and Reviewboard. I will add an option to disable it in plugin configuration.
