### ISSUE TITLE
Support "depends on" patches

### ISSUE THREAD

**Issue by misery** [vmware/jenkins-reviewbot#22]
Hi! :-)

Reviewboard supports a "parent diff" [1] for a review request on upload through the API or Draft-Mode. If the reviewbot downloads the diff to apply it, the "parent diff" isn't downloaded. So the patch result isn't correct or the patch cannot be applied after all.

It seems that reviewboard does not support a download of the "parent diff" to be applied before the diff. Also the "parent diff" could be out-dated if the "parent" of the review is already pushed to the repository.

I think the best workflow is to use "depends on" fields of reviewboard. So the reviewbot needs to read all "depends on" entries in the correct order and provide an additional "depends.diff" beside the "patch.diff" of all downloaded "depends on"-review-requests. Of course.... only those that are not marked as submitted or discarded.
 
What do you think? The biggest problems would be to collect all depends-on diffs in the right order. Specially if there are multiple depends-on that will have multiple depends-on, too.

[1] https://www.reviewboard.org/docs/manual/2.0/webapi/2.0/resources/diff-list/#POST_params

**Comment by yardena** [comment]
Sounds a bit problematic to me. IMHO if someone is making a series of changes that need to be reviewed, it's better to use a branch, and not a series of review requests. The plugin already supports building on a branch.

**Comment by misery** [comment]
But how can I test a review with a patch that cannot be applied because the parent changeset of that patch (parent diff) in still in review on not pushed to repository? Another branch won't help here because it won't be pushed to repository. So I can't build a review until it's parent is in repository. But this can take some time if I have a lot of depending changesets.

Series of patches is used on gerrit, too.
